launches {
    time: 5
    angle_pos: 15
    is_accurate: True
}

launches {
    time: 10
    angle_pos: 45
    is_accurate: True
}

launches {
    time: 15
    angle_pos: 75
    is_accurate: True
}

launches {
    time: 20
    angle_pos: 105
    is_accurate: True
}

launches {
    time: 25
    angle_pos: 135
    is_accurate: True
}

launches {
    time: 30
    angle_pos: 165
    is_accurate: True
}

# proto-file: proto/scenario.proto
# proto-message: Proto::TargetScenario
