launches {
    time: 0
    angle_pos: 45
    priority: 0.3
    is_accurate: true
}

launches {
    time: 20
    angle_pos: 135
    priority: 0.7
    is_accurate: true
}

# proto-file: proto/scenario.proto
# proto-message: Proto::TargetScenario
