radar_start_angle: 150

launches {
    time: 0
    angle_pos: 30
    is_accurate: true
    priority: 0.5
    abs_speed_share: 1
}

# proto-file: proto/scenario.proto
# proto-message: Proto::TargetScenario
