description: "simple example of work"

launches {
    time: 0
    angle_pos: 55
    angle_deviation: 7
    priority: 0.1
    abs_speed_share: 1.0
}

launches {
    time: 40
    angle_pos: 125
    is_accurate: true
    priority: 0.8
}

launches {
    time: 70
    angle_pos: 85
    is_accurate: true
    priority: 0.5
}

launches {
    time: 100
    angle_pos: 170
    is_accurate: true
    priority: 0.9
}

# proto-file: proto/scenario.proto
# proto-message: Proto::TargetScenario
