radar_start_angle: 90

launches {
    time: 0
    angle_pos: 120
    is_accurate: true
    priority: 0.6
    abs_speed_share: 1.0
}

launches {
    time: 10
    angle_pos: 145
    is_accurate: true
    priority: 0.7
    abs_speed_share: 1.0
}

launches {
    time: 40
    angle_pos: 40
    is_accurate: true
    priority: 1.0
    abs_speed_share: 1.0
}

# proto-file: proto/scenario.proto
# proto-message: Proto::TargetScenario
