launches {
    time: 0
    angle_pos: 90
    is_accurate: true
    priority: 0.7
    abs_speed_share: 0.7
}

launches {
    time: 10
    angle_pos: 170
    is_accurate: true
    priority: 0.3
    abs_speed_share: 0.7
}

launches {
    time: 40
    angle_pos: 130
    is_accurate: true
    priority: 0.8
    abs_speed_share: 0.7
}

launches {
    time: 80
    angle_pos: 70
    is_accurate: true
    priority: 0.6
    abs_speed_share: 0.7
}

# proto-file: proto/scenario.proto
# proto-message: Proto::TargetScenario
