radar_start_angle: 30

launches {
    time: 0
    angle_pos: 45
    is_accurate: true
    priority: 0.5
    abs_speed_share: 1
}

launches {
    time: 30
    angle_pos: 110
    is_accurate: true
    priority: 0.8
    abs_speed_share: 1
}

# proto-file: proto/scenario.proto
# proto-message: Proto::TargetScenario
