radar_start_angle: 90
ship_start_angle: 0
description: "Multiple targets arriving in quick succession from sector of responsibility"
launches {
    time: 0
    angle_pos: 90
    is_accurate: true
    priority: 0.8
    abs_speed_share: 0.9
}
launches {
    time: 25
    angle_pos: 100
    is_accurate: true
    priority: 0.9
    abs_speed_share: 0.8
}
launches {
    time: 50
    angle_pos: 80
    is_accurate: true
    priority: 0.7
    abs_speed_share: 0.7
}
launches {
    time: 75
    angle_pos: 110
    is_accurate: true
    priority: 0.6
    abs_speed_share: 0.8
}
launches {
    time: 100
    angle_pos: 70
    is_accurate: true
    priority: 0.9
    abs_speed_share: 0.9
}
launches {
    time: 125
    angle_pos: 120
    is_accurate: true
    priority: 0.8
    abs_speed_share: 0.8
}
launches {
    time: 150
    angle_pos: 60
    is_accurate: true
    priority: 0.7
    abs_speed_share: 0.7
}
launches {
    time: 175
    angle_pos: 130
    is_accurate: true
    priority: 0.9
    abs_speed_share: 0.9
}
launches {
    time: 200
    angle_pos: 50
    is_accurate: true
    priority: 0.8
    abs_speed_share: 0.8
}

# proto-file: proto/scenario.proto
# proto-message: Proto::TargetScenario
