radar_start_angle: 90
ship_start_angle: 0
description: "Alternating attacks between both blind spot regions"
launches {
    time: 0
    angle_pos: 50
    is_accurate: true
    priority: 0.8
    abs_speed_share: 0.8
}
launches {
    time: 30
    angle_pos: 130
    is_accurate: true
    priority: 0.8
    abs_speed_share: 0.8
}
launches {
    time: 60
    angle_pos: 40
    is_accurate: true
    priority: 0.7
    abs_speed_share: 0.9
}
launches {
    time: 90
    angle_pos: 140
    is_accurate: true
    priority: 0.7
    abs_speed_share: 0.9
}
launches {
    time: 120
    angle_pos: 60
    is_accurate: true
    priority: 0.9
    abs_speed_share: 0.7
}
launches {
    time: 150
    angle_pos: 125
    is_accurate: true
    priority: 0.9
    abs_speed_share: 0.7
}
launches {
    time: 180
    angle_pos: 35
    is_accurate: true
    priority: 0.6
    abs_speed_share: 1.0
}
launches {
    time: 210
    angle_pos: 144
    is_accurate: true
    priority: 0.6
    abs_speed_share: 1.0
}
launches {
    time: 240
    angle_pos: 90
    is_accurate: true
    priority: 1.0
    abs_speed_share: 1.0
}

# proto-file: proto/scenario.proto
# proto-message: Proto::TargetScenario
