small_radar {
    radius: 400
    view_angle: 60
    frequency: 20
    max_eps: 0.2
    max_angle_speed: 2
    rad_stddev: 0.2
    ang_stddev: 0.04
    h_stddev: 0.1
    responsible_sector_start: 45
    responsible_sector_end: 135

    dead_zone {
        start: 20
        end: 30
    }
}

big_radar {
    radius: 700
    frequency: 0.5
    rad_stddev: 1
    ang_stddev: 0.2
    h_stddev: 0.5
}

general {
    death_time: 2500
    play_speed: 5.0
    big_radar_measure_cnt: 60
    small_radar_measure_cnt: 100
    aprox_small_radar_measure_cnt: 50
    margin_angle: 3
    margin_time: 5000
}

defense {
    time_to_launch_rocket: 3000
    rocket_speed: 5
}

simulator {
    targets_per_minute: 2
    min_target_speed: 1
    max_target_speed: 2
    max_deviation_angle_vertical: 10
    max_height: 250
    probability_of_accurate_missile: 0.4
    random_seed: 40
}

visualizer {
    radars_outline_thickness: 1
    target_radius: 5
    draw_entry_points: true
}

# proto-file: proto/params.proto
# proto-message: Proto::Parameters
