small_radar {
    radius: 400
    view_angle: 60
    frequency: 20
    angle_speed: 5
    rad_error: 0.6
    ang_error: 0.1
    h_error: 0.2
    responsible_sector_start: 45
    responsible_sector_end: 135
}

big_radar {
    radius: 700
    frequency: 0.5
    rad_error: 3
    ang_error: 0.6
    h_error: 2
}

general {
    death_time: 2500
    play_speed: 1.0
}

defense {
    time_to_launch_rocket: 3000
    rocket_speed: 0.06
}

simulator {
    targets_per_minute: 2
    min_target_speed: 0.005
    max_target_speed: 0.01
    max_deviation_angle_vertical: 10
    max_height: 250
    probability_of_accurate_missile: 0.4
    random_seed: 40
}

visualizer {
    radars_outline_thickness: 1
    target_radius: 5
}

# proto-file: proto/params.proto
# proto-message: Proto::Parameters
